# Generated by Django 4.1.1 on 2022-10-05 02:02

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("laptopaccessories", "Laptop & accessories"),
                    ("electronics", "electronics"),
                    ("apparel", "Apparel"),
                ],
                default=builtins.all,
                max_length=500,
                null=True,
            ),
        ),
    ]
