# Generated by Django 4.1.1 on 2022-10-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all", "All"),
                            ("laptopaccessories", "Laptop & accessories"),
                            ("electronics", "electronics"),
                            ("apparel", "Apparel"),
                            ("smartphones", "Smartphones"),
                        ],
                        default="all",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.category",
            ),
        ),
    ]
